### ISSUE TITLE
Windows toolchain builds are now broken, missing static Snappy library

### ISSUE THREAD

**Issue by wesm** [conda-forge/snappy-feedstock#13]
In https://github.com/conda-forge/arrow-cpp-feedstock we are linking statically to Snappy on all platforms. The recent 1.1.6 Windows build does not include a static .lib file. Can you either remove the build or update it to include a library `snappystatic.lib`? Things were working fine on defaults before. Thanks

cc @maxris @xhochy 

see also https://github.com/conda-forge/pyarrow-feedstock/pull/35

It looks like we can triage the situation by including snappy in the runtime scope for arrow-cpp, so I will do that now

**Comment by jakirkham** [comment]
First we haven't made any Windows builds in `conda-forge` yet. So would check where the packages are coming from (`defaults`?) and raise this with them.

Second we do plan to make Windows builds. However it doesn't seem that snappy's CMake builds support anything other than the dynamic libraries. So it would require some patching to fix this. It's unclear at this time as to what that would entail. Also no one has stepped forward to do this patching or submit it upstream at this time.

**Comment by wesm** [comment]
Sorry for the friendly fire, I guess the problem is caused by defaults, then, when they upgraded to 1.1.6.

**Comment by wesm** [comment]
Where do I report such problems?

@Maxris could you submit a patch to enable CMake build with static libraries? We can use the one from Apache Arrow https://github.com/apache/arrow/blob/master/cpp/cmake_modules/SnappyCMakeLists.txt

**Comment by jakirkham** [comment]
> Sorry for the friendly fire...

No worries. TBH it is good timing as we were just finishing up a PR for dynamic libraries on Windows, but were stuck trying to come up with something for static libraries.

> ...I guess the problem is caused by defaults, then, when they upgraded to 1.1.6.

That would be my guess as well. I think they were carrying around their own Visual Studio project files before. So they are probably pretty eager to stop maintaining those.

> Where do I report such problems?

Would report to this [issue tracker]( https://github.com/ContinuumIO/anaconda-recipes/issues ). Though it doesn't seem they have open sourced their most recent changes.

> @MaxRis could you submit a patch to enable CMake build with static libraries?

So we do have PR ( https://github.com/conda-forge/snappy-feedstock/pull/12 ) with dynamic libraries. It would be good if we could integrate that work into a patch that can be applied there. If we are able to accomplish this, it should make it easier to upstream that patch to Google's snappy to simplify future builds. Copying @dougalsutherland who wrote that PR.

**Comment by maxhora** [comment]
@jakirkham @wesm sure, will check how to combine #12 with static libs build

**Comment by maxhora** [comment]
@dougalsutherland @jakirkham @wesm [PR](https://github.com/dougalsutherland/snappy-feedstock/pull/1) into branch of #12

**Comment by jakirkham** [comment]
So we should now (or soon) have Windows builds with dynamic and static libraries thanks to all the work done in PR ( https://github.com/conda-forge/snappy-feedstock/pull/12 ). This should resolve the concern raised here. As such will close this out.

That said, feel free to follow-up with `defaults` about the missing static libraries. Perhaps they can reuse our recipe to rebuild their packages.
