### ISSUE TITLE
snappy 1.1.8 assumes BMI2

### ISSUE THREAD

**Issue by mparry** [conda-forge/snappy-feedstock#24]
The 1.1.8 package of `snappy` (and probably earlier) appears to be built, for Windows at least, to assume the presence of the BMI2 instruction set. That can be seen in the 1.1.8 build log here:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=115252&view=logs&j=2cc45e14-23e3-52d7-b33a-8c2744410b97&t=21c44aa7-1ae3-5312-cacc-7f19fefc82f4

We have consequently found that `arrow` crashes with a Windows illegal instruction error (0xc000001d) for `BZHI` when used on a machine whose CPU lacks AVX2 support. Presumably this code in `snappy` is being hit:

https://github.com/google/snappy/blob/1.1.8/snappy.cc#L717-L728

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
arrow-cpp: 0.17.1-py37h1234567_4_cpu
parquet-cpp: 1.5.1-2
pyarrow: 0.17.1-py37h1234567_4_cpu
snappy: 1.1.8-he025d50_1
```
</details>

**Comment by xhochy** [comment]
Looking the patch https://github.com/google/snappy/commit/4f0adca400ed519c463f8bbc3031296e38dd746d (included in 1.1.8), we shouldn't be using these instructions anymore. Are you sure that snappy is the source of the illegal instruction?

**Comment by mparry** [comment]
Sure, I saw that change, but as per my [first link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=115252&view=logs&j=2cc45e14-23e3-52d7-b33a-8c2744410b97&t=21c44aa7-1ae3-5312-cacc-7f19fefc82f4) (to the 1.1.8 build) it seems to be determining that `SNAPPY_HAVE_BMI2` should be enabled and therefore the instruction is being used, I think.

```
-- Performing Test SNAPPY_HAVE_BMI2
-- Performing Test SNAPPY_HAVE_BMI2 - Success
```

**Comment by xhochy** [comment]
It is check for but not used, see the above linked patch. The option is only set if also `SNAPPY_REQUIRE_AVX2` was set.

**Comment by xhochy** [comment]
Please reopen if you have a better method for determing whether the instruction is present. I don't want to say it isn't present, it is just not in snappy itself.

**Comment by mparry** [comment]
It seems I don't have permissions to re-open the issue, but I do think that it should be re-opened.

I agree with you about what that patch was _supposed_ to do but unfortunately I don't think it works correctly. If I inspect, for example, `snappy_static.lib` present in the `snappy-1.1.8-he025d50_1` package using `dumpbin` then I can see the `BZHI` instruction present:

```
?ExtractLowBytes@snappy@@YAIIH@Z (unsigned int __cdecl snappy::ExtractLowBytes(unsigned int,int)):
  0000000000000000: 8D 04 D5 00 00 00  lea         eax,[rdx*8+0000000000000000h]
                    00
  0000000000000007: C4 E2 78 F5 C1     bzhi        eax,ecx,eax
  000000000000000C: C3                 ret
```

The optimised `ExtractLowBytes()` implementation is only guarded by `SNAPPY_HAVE_BMI2` and this _is_ being enabled by cmake's `CheckCXXSourceCompiles` module - `SNAPPY_HAVE_BMI2` is the `resultVar` and will be set if the check passes.

I think the fundamental issue is that the test being used for BMI2 support is not, AFAICS, the right approach on Windows. The sample program

```c++
#include <immintrin.h>
int main() {
  return _bzhi_u32(0, 1);
}
```

will compile _regardless_ of compiler flags on Windows. I believe this is contrary to the clang and/or GCC cases, where the intrinsincs are not available by default.

(In contrast, the approach used [at the top of `snappy.cc`](https://github.com/google/snappy/blob/master/snappy.cc#L52-L56) would actually work correctly, I think, but it isn't hit because `SNAPPY_HAVE_BMI2` is already defined by then.)

**Comment by mparry** [comment]
A quick further test with the newer builds (i.e. with a dynamically linked `snappy`) further backs this up; it dies on a `BZHI` instruction with the following stack:

```
>    snappy.dll!00007ffaa67d1e71()    Unknown
     snappy.dll!00007ffaa67d4cdf()    Unknown
     arrow.dll!00007ffa9e199c56()    Unknown
     parquet.dll!00007ffa9dca0869()    Unknown
     parquet.dll!00007ffa9dcb40aa()    Unknown
     parquet.dll!00007ffa9dcb8c3f()    Unknown
     parquet.dll!00007ffa9dcba856()    Unknown
     parquet.dll!00007ffa9dcb2dbd()    Unknown
     parquet.dll!00007ffa9dcbc499()    Unknown
     parquet.dll!00007ffa9dcc93c2()    Unknown
     arrow.dll!00007ffa9e1ae557()    Unknown
     arrow.dll!00007ffa9e1aec7d()    Unknown
     arrow.dll!00007ffa9e1ae779()    Unknown
     ucrtbase.dll!00007ffab606c1ae()    Unknown
     kernel32.dll!00007ffac67413d2()    Unknown
     ntdll.dll!00007ffac69454f4()    Unknown
```

(PDBs don't seem to be available for these builds, otherwise we could offer something more illuminating!)

**Comment by wesm** [comment]
This seems to be the root cause of https://issues.apache.org/jira/browse/ARROW-7939

**Comment by pitrou** [comment]
Was the issue reported to the Snappy project?

**Comment by pitrou** [comment]
> Was the issue reported to the Snappy project?

Apparently not :-(
