### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/snappy-feedstock#4]
Could you please take a look at this @msarahan?

**Comment by msarahan** [comment]
Sorry, I'm not clear what the problem is, and I don't have time to dig into it from the beginning.  If you have specific questions, I'm happy to try to help.

**Comment by jakirkham** [comment]
Maybe we should ask @groutr about it actually. Basically a VC project file was included here, but I have no clue what we are doing with it. Also, I don't believe it was working previously.

**Comment by jakirkham** [comment]
Maybe it will be better to just wait for the outcome of PR ( https://github.com/google/snappy/pull/16 ).

**Comment by martindurant** [comment]
Any advance here? A conda build exists [here](https://anaconda.org/willyd/snappy/files).

**Comment by jakirkham** [comment]
Still waiting to see what the outcome of PR ( https://github.com/google/snappy/pull/16 ) is.

**Comment by djsutherland** [comment]
https://github.com/google/snappy/pull/16 has merged; see #10.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/snappy-feedstock/pull/12 ).
